version: 1
formatters:
  detailed:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: detailed
    filename: logs/car_control.log
    maxBytes: 5242880
    backupCount: 3
  console:
    class: logging.StreamHandler
    formatter: detailed
loggers:
  '':
    level: DEBUG
    handlers: [file, console]